/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-10-20 01:39:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta name=\"keywords\" content=\"\" />\n");
      out.write("        <meta name=\"description\" content=\"\" />\n");
      out.write("        <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("        <title>Sondage</title>\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600' rel='stylesheet' type='text/css'>\n");
      out.write("        <link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div id=\"wrapper\">\n");
      out.write("            <div id=\"header-wrapper\">\n");
      out.write("                <div id=\"header\">\n");
      out.write("                    <div id=\"logo\">\n");
      out.write("                        <h1><a href=\"#\">Escalate</a></h1>\n");
      out.write("                        <p>Template Design by <a href=\"http://www.freecsstemplates.org/\" rel=\"nofollow\">FreeCSSTemplates.org</a></p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- end #header -->\n");
      out.write("            <div id=\"menu\">\n");
      out.write("                <ul>\n");
      out.write("                    <li class=\"current_page_item\">\n");
      out.write("                    <a href=\"#\">Acceuil</a></li>\n");
      out.write("                    <li><a href=\"#\">Sondages Faits</a></li>\n");
      out.write("                    \n");
      out.write("                    ");
 if(session.getAttribute("connexion") == null) out.println("<li><a href='Inscription.jsp'>Inscription</a></li>"); 
      out.write("\n");
      out.write("                    <li><a href=");
 if(session.getAttribute("connexion") != null) out.println("Deconnexion.jsp"); else out.println("Connexion.jsp"); 
      out.write('>');
 if(session.getAttribute("connexion") != null) out.println("Déconnexion"); else out.println("Connexion"); 
      out.write(" </a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <!-- end #menu -->\n");
      out.write("            <div id=\"page\">\n");
      out.write("                <div id=\"page-bgtop\">\n");
      out.write("                    <div id=\"page-bgbtm\">\n");
      out.write("                        <div id=\"content\">\n");
      out.write("                            <div class=\"post\">\n");
      out.write("                                <h2 class=\"title\"><a href=\"#\">Welcome to Escalate</a></h2>\n");
      out.write("                                <p class=\"meta\">Posted by <a href=\"#\">Someone</a> on July 08, 2013\n");
      out.write("                                    &nbsp;&bull;&nbsp; <a href=\"#\" class=\"comments\">Comments (64)</a> &nbsp;&bull;&nbsp; <a href=\"#\" class=\"permalink\">Full article</a></p>\n");
      out.write("                                <div class=\"entry\"> <a href=\"#\" class=\"image image-full\"><img src=\"images/pics01.jpg\" alt=\"\" /></a>\n");
      out.write("                                    <p>This is <strong>Escalate</strong>, a free, fully standards-compliant CSS template designed by <a href=\"http://www.freecsstemplates.org/\" rel=\"nofollow\">FreeCSSTemplates.org</a>. The photos in this template are from <a href=\"http://fotogrph.com/\"> Fotogrph</a>. This free template is released under a <a href=\"http://creativecommons.org/licenses/by/3.0/\">Creative Commons Attributions 3.0</a> license, so you are pretty much free to do whatever you want with it (even use it commercially) provided you keep the links in the footer intact. Aside from that, have fun with it :) </p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"post\">\n");
      out.write("                                <h2 class=\"title\"><a href=\"#\">Lorem ipsum sed aliquam</a></h2>\n");
      out.write("                                <p class=\"meta\">Posted by <a href=\"#\">Someone</a> on July 7, 2013\n");
      out.write("                                    &nbsp;&bull;&nbsp; <a href=\"#\" class=\"comments\">Comments (64)</a> &nbsp;&bull;&nbsp; <a href=\"#\" class=\"permalink\">Full article</a></p>\n");
      out.write("                                <div class=\"entry\"> <a href=\"#\" class=\"image image-full\"><img src=\"images/pics02.jpg\" alt=\"\" /></a>\n");
      out.write("                                    <p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href=\"#\">dapibus semper urna</a>. Pellentesque ornare, consectetuer nisl felis ac diam. Sed lacus. Donec lectus. Nullam pretium nibh ut turpis.</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"post\">\n");
      out.write("                                <h2 class=\"title\"><a href=\"#\">Phasellus pellentesque turpis </a></h2>\n");
      out.write("                                <p class=\"meta\">Posted by <a href=\"#\">Someone</a> on July 8, 2013\n");
      out.write("                                    &nbsp;&bull;&nbsp; <a href=\"#\" class=\"comments\">Comments (64)</a> &nbsp;&bull;&nbsp; <a href=\"#\" class=\"permalink\">Full article</a></p>\n");
      out.write("                                <div class=\"entry\"> <a href=\"#\" class=\"image image-full\"><img src=\"images/pics01.jpg\" alt=\"\" /></a>\n");
      out.write("                                    <p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc. Donec ipsum. Proin imperdiet est. Pellentesque ornare.</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div style=\"clear: both;\">&nbsp;</div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- end #content -->\n");
      out.write("                        <div id=\"sidebar\">\n");
      out.write("                            <ul>\n");
      out.write("                                <li>\n");
      out.write("                                    <h2>Aliquam tempus</h2>\n");
      out.write("                                    <p>Mauris vitae nisl nec metus placerat perdiet est. Phasellus dapibus semper consectetuer hendrerit.</p>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <h2>Categories</h2>\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li><a href=\"#\">Aliquam libero</a></li>\n");
      out.write("                                        <li><a href=\"#\">Consectetuer adipiscing elit</a></li>\n");
      out.write("                                        <li><a href=\"#\">Metus aliquam pellentesque</a></li>\n");
      out.write("                                        <li><a href=\"#\">Suspendisse iaculis mauris</a></li>\n");
      out.write("                                        <li><a href=\"#\">Urnanet non molestie semper</a></li>\n");
      out.write("                                        <li><a href=\"#\">Proin gravida orci porttitor</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <h2>Blogroll</h2>\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li><a href=\"#\">Aliquam libero</a></li>\n");
      out.write("                                        <li><a href=\"#\">Consectetuer adipiscing elit</a></li>\n");
      out.write("                                        <li><a href=\"#\">Metus aliquam pellentesque</a></li>\n");
      out.write("                                        <li><a href=\"#\">Suspendisse iaculis mauris</a></li>\n");
      out.write("                                        <li><a href=\"#\">Urnanet non molestie semper</a></li>\n");
      out.write("                                        <li><a href=\"#\">Proin gravida orci porttitor</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <h2>Archives</h2>\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li><a href=\"#\">Aliquam libero</a></li>\n");
      out.write("                                        <li><a href=\"#\">Consectetuer adipiscing elit</a></li>\n");
      out.write("                                        <li><a href=\"#\">Metus aliquam pellentesque</a></li>\n");
      out.write("                                        <li><a href=\"#\">Suspendisse iaculis mauris</a></li>\n");
      out.write("                                        <li><a href=\"#\">Urnanet non molestie semper</a></li>\n");
      out.write("                                        <li><a href=\"#\">Proin gravida orci porttitor</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <h2>Links</h2>\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li><a href=\"#\">Aliquam libero</a></li>\n");
      out.write("                                        <li><a href=\"#\">Consectetuer adipiscing elit</a></li>\n");
      out.write("                                        <li><a href=\"#\">Metus aliquam pellentesque</a></li>\n");
      out.write("                                        <li><a href=\"#\">Suspendisse iaculis mauris</a></li>\n");
      out.write("                                        <li><a href=\"#\">Urnanet non molestie semper</a></li>\n");
      out.write("                                        <li><a href=\"#\">Proin gravida orci porttitor</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- end #sidebar -->\n");
      out.write("                        <div style=\"clear: both;\">&nbsp;</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- end #page --> \n");
      out.write("        </div>\n");
      out.write("        <div id=\"footer\">\n");
      out.write("            <p>Copyright (c) 2013 Sitename.com. All rights reserved. | Photos by <a href=\"http://fotogrph.com/\">Fotogrph</a> | Design by <a href=\"http://www.freecsstemplates.org/\" rel=\"nofollow\">FreeCSSTemplates.org</a>.</p>\n");
      out.write("        </div>\n");
      out.write("        <!-- end #footer -->\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
